library(plyr)
library(tidyr)
library(tidyverse)
library(shiny)
library(shinyWidgets)
library(ggplot2)
library(plotly)
library(shinyalert)
library(DT)
library(shinycssloaders)
library(tictoc)
library(bslib)
library("aws.s3")
library(glmmTMB)
library(stats)
library(reactlog)
library(pryr)
library(memoise)
library(profvis)
library(rlist)
library(shinyjs)
library(combinat)
library(doParallel)
library(foreach)
library("data.table")
library(rhandsontable)
library(lubridate)
library(quantmod)
library(quantreg)
library(xts)

## Define Financial Tricker choices based on financial instruments type
Stocks.Tickers <- read.csv("StockListsIDX.csv")
Stocks.Tickers <- c("BBCA", "BBRI", "INDF", "ANTM", "WIKA", "TLKM", "UNVR")
ETF.Tickers <- c("ETF1", "ETF2", "ETF3")
Bonds.Tickers <- c("Bonds1", "Bonds2", "Bonds3")
