ui <- fluidPage(
    # theme = bs_theme(version = 3, bootswatch = "journal"),
    
    # Application title
    titlePanel(strong("Enigma Trading")),
    br(),
    
    # Code for sidebar layout
    sidebarPanel(
        conditionalPanel(condition = "input.tabselected==1",
                         align = "left",
                         tags$h3("Financial Instruments"),
                         pickerInput(inputId = "FinInstrument", 
                                     label = "Select Financial Instruments", 
                                     choices = c("Stocks", "ETF", "Bonds"), 
                                     selected = "Stocks"), 
                         ## Reactive Dropdown Selections of Financial tricker corresponds to Instruments selections
                         pickerInput(inputId = "FinTicker", 
                                     label = "Select Ticker", 
                                     choices = "",
                                     options = list(`live-search` = TRUE, `actions-box` = TRUE),
                                     multiple = T),
                         ## Period Slider
                         dateRangeInput(inputId = "DatesRange",
                                     label = "Dates:",
                                     start = "2019-01-01",
                                     end = paste(Sys.Date())), 
                         ## Input for table/chart representation
                         # pickerInput(inputId = "Format", 
                         #             label = "Data Representation", 
                         #             choices = c("Table", "Graph"), 
                         #             multiple = F), 
                         ## Action Button to represent the data
                         br(),
                         actionBttn(inputId = "ShowData", block = T,
                                       label = "Show Data",
                                       style = "unite", 
                                       color = "primary",
                                       icon = icon("table"), size = "lg")),
        
        conditionalPanel(condition = "input.tabselected==2",
                         align = "left",
                         tags$h3("Financial Instruments"),
                         pickerInput(inputId = "Sel.TickerViz", 
                                     label = "Select Financial Instruments", 
                                     choices = ""), 
                         br(),
                         actionBttn(inputId = "ShowViz", block = T,
                                    label = "Show Visualization",
                                    style = "unite", 
                                    color = "primary",
                                    icon = icon("table"), size = "md"), 
                         br(), br(),
                         ##Add dropdown for charting indicator analysis
                         dropdown(
                             inputId = "IndicatorDropdown",
                             label = "Add Technical Indicator",
                             tags$h3("Technical Indicator"),
                             dropdown(
                                 inputId = "MADropdown",
                                 label = "Moving Average",
                                 tags$h3("MA Indicator"),
                                 numericInput(inputId =  "MA1",
                                              label = "MA 1", 
                                              min = 0, max = 50, step = 2,
                                              value = 20),
                                 numericInput(inputId =  "MA2",
                                              label = "MA 1", 
                                              min = 0, max = 50, step = 2,
                                              value = 20),
                                 numericInput(inputId =  "MA3",
                                              label = "MA 3", 
                                              min = 0, max = 50, step = 2,
                                              value = 20)), 
                             br(),
                             #Bollinger Bands
                             dropdown(
                                 inputId = "BBDropdown",
                                 label = "BB Indicator",
                                 tags$h3("BB Indicator"),
                                 numericInput(inputId =  "BB.low",
                                              label = "Low Band", 
                                              min = 0, max = 50, step = 2,
                                              value = 20),
                                 numericInput(inputId =  "BB.high",
                                              label = "Upper Band", 
                                              min = 0, max = 50, step = 2,
                                              value = 20),
                                 numericInput(inputId =  "BB.sma",
                                              label = "SMA", 
                                              min = 0, max = 50, step = 2,
                                              value = 20)), 
                             br(),
                             actionBttn(inputId = "AddIndicatorViz", block = T,
                                        label = "Add Indicator",
                                        style = "unite", 
                                        color = "primary",
                                        icon = icon("table"), size = "md")
                             
                             )),
        width = 3), 
    mainPanel(
        tabsetPanel(type = "tabs", id = "tabselected", selected = 1,
                    tabPanel("Table Representation",
                             DT::dataTableOutput("TickerDataTable", width = "100%"),
                             value = 1), 
                    tabPanel("Visualization",
                             plotOutput("TickerDataViz", height = "700px"),
                             value = 2))))

