ui <- fluidPage(
    # theme = bs_theme(version = 3, bootswatch = "journal"),
    
    # Application title
    titlePanel(strong("Enigma Trading")),
    br(),
    
    # Code for sidebar layout
    sidebarPanel(
        conditionalPanel(condition = "input.tabselected==1",
                         align = "left",
                         tags$h3("Financial Instruments"),
                         pickerInput(inputId = "FinInstrument", 
                                     label = "Select Financial Instruments", 
                                     choices = c("Stocks", "ETF", "Bonds"), 
                                     selected = "Stocks"), 
                         ## Reactive Dropdown Selections of Financial tricker corresponds to Instruments selections
                         pickerInput(inputId = "FinTicker", 
                                     label = "Select Ticker", 
                                     choices = "",
                                     options = list(`live-search` = TRUE, `actions-box` = TRUE),
                                     multiple = T),
                         ## Period Slider
                         dateRangeInput(inputId = "DatesRange",
                                     label = "Dates:",
                                     start = "2019-01-01",
                                     end = paste(Sys.Date())), 
                         br(),
                         actionBttn(inputId = "ShowData", block = T,
                                       label = "Show Data",
                                       style = "unite", 
                                       color = "primary",
                                       icon = icon("table"), size = "lg")),
        
        conditionalPanel(condition = "input.tabselected==2",
                         align = "left",
                         tags$h3("Financial Instruments"),
                         pickerInput(inputId = "Sel.TickerViz", 
                                     label = "Select Financial Instruments", 
                                     choices = ""), 
                         
                         ##Add dropdown for charting indicator analysis
                         dropdown(
                             inputId = "IndicatorDropdown",
                             label = "Add Technical Indicator",
                             tags$h3("Technical Indicator"),
                             dropdown(
                                 inputId = "MADropdown",
                                 label = "Moving Average",
                                 tags$h3("MA Indicator"),
                                 numericInput(inputId =  "MA1",
                                              label = "MA 1", 
                                              min = 0, max = 50, step = 2,
                                              value = 20),
                                 numericInput(inputId =  "MA2",
                                              label = "MA 1", 
                                              min = 0, max = 50, step = 2,
                                              value = 20),
                                 numericInput(inputId =  "MA3",
                                              label = "MA 3", 
                                              min = 0, max = 50, step = 2,
                                              value = 20)), 
                             br(),
                             #Bollinger Bands
                             dropdown(
                                 inputId = "BBDropdown",
                                 label = "BB Indicator",
                                 tags$h3("BB Indicator"),
                                 numericInput(inputId =  "BB.MAperiod",
                                              label = "MA Period", 
                                              min = 0, max = 50, step = 2,
                                              value = 20),
                                 numericInput(inputId =  "BB.sdev",
                                              label = "Standard Deviation", 
                                              min = 0.1, max = 2, step = 0.1,
                                              value = 1))), 
                         br(), br(),
                         actionBttn(inputId = "ShowViz", block = T,
                                    label = "Show Visualization",
                                    style = "unite", 
                                    color = "primary",
                                    icon = icon("table"), size = "md")),
        
        conditionalPanel(condition = "input.tabselected==3",
                         align = "left",
                         tags$h3("Financial Data Summary"), 
                         ## Reactive Dropdown Selections of Financial tricker corresponds to Instruments selections
                         pickerInput(inputId = "FinTicker.FinSummary", 
                                     label = "Select Ticker", 
                                     choices = "",
                                     options = list(`live-search` = TRUE, `actions-box` = TRUE),
                                     multiple = F),
                         ## Period Slider
                         dateRangeInput(inputId = "DatesRange.FinSummary",
                                        label = "Dates:",
                                        start = "2019-01-01",
                                        end = paste(Sys.Date())), 
                         ## Input for table/chart representation
                         pickerInput(inputId = "AnalType.FinSummary",
                                     label = "Summary Type",
                                     choices = c("Log Return", "Simple Return", "Return Distribution"),
                                     selected = "Log Return",
                                     multiple = F),
                         br(),
                         actionBttn(inputId = "ShowData.FinSummary", block = T,
                                    label = "Show Data",
                                    style = "unite", 
                                    color = "primary",
                                    icon = icon("table"), size = "md")),
        width = 3), 
    mainPanel(
        tabsetPanel(type = "tabs", id = "tabselected", selected = 1,
                    tabPanel("Table Representation",
                             DT::dataTableOutput("TickerDataTable", width = "100%"),
                             value = 1), 
                    tabPanel("Visualization",
                             plotOutput("TickerDataViz", height = "700px"),
                             value = 2), 
                    navbarMenu("Statistical Analysis",
                               ## Sub Tab panel
                               tabPanel("Statistical Summary",
                                        plotOutput("SummaryPlot", height = "700px"),
                                        plotOutput("SummaryTable", height = "700px"),
                                        value = 3),
                               tabPanel("Statistical Test",
                                        plotOutput("AutocorrPlot", height = "700px"),
                                        value = 4), 
                               tabPanel("Statistical Predictions",
                                        plotOutput("StatsPredictions", height = "700px"),
                                        value = 5), 
                               tabPanel("Statistical Simulations",
                                        plotOutput("StatsSims", height = "700px"),
                                        value = 6))
                    )))

